// Turns the shared repo-root `icons/*.svg` set into TypeScript modules the
// library can compile: ng-packagr has no `.svg` loader, and the folder sits
// outside the library's rootDir anyway. Emits one module per icon (so each
// stays a lazy chunk for consumers) plus an index with the name list and the
// `import()` loaders. The output is gitignored — rerun after adding an svg.
//
//   node scripts/generate-icons.mjs

import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ICONS_DIR = fileURLToPath(new URL('../../icons/', import.meta.url));
const OUT_DIR = fileURLToPath(
  new URL('../projects/lumen-ui/src/lib/components/ui/icon/svg/', import.meta.url),
);

const HEADER = '// Generated by scripts/generate-icons.mjs from the repo-root icons/ folder. Do not edit.\n';

const names = readdirSync(ICONS_DIR)
  .filter((file) => file.endsWith('.svg'))
  .map((file) => file.slice(0, -'.svg'.length))
  .sort();

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

for (const name of names) {
  const svg = readFileSync(`${ICONS_DIR}${name}.svg`, 'utf8').trim();
  writeFileSync(`${OUT_DIR}${name}.ts`, `${HEADER}export default ${JSON.stringify(svg)};\n`);
}

const index = [
  HEADER,
  `export const ICON_NAMES = [\n${names.map((n) => `  '${n}',`).join('\n')}\n] as const;\n`,
  'export const ICON_LOADERS: Readonly<Record<string, () => Promise<{ default: string }>>> = {',
  ...names.map((n) => `  '${n}': () => import('./${n}'),`),
  '};\n',
].join('\n');
writeFileSync(`${OUT_DIR}index.ts`, index);

console.log(`[generate-icons] ${names.length} icons → ${OUT_DIR}`);
